version: 0.2
env:
  secrets-manager:
    DOCKERHUB_USERNAME: "dbsupervisor/docker-hub:DOCKERHUB_USERNAME"
    DOCKERHUB_PASSWORD: "dbsupervisor/docker-hub:DOCKERHUB_PASSWORD"
artifacts:
  files: imagedefinitions.json
phases:
  install:
    commands:
      - apt-get update
      - apt install jq
  pre_build:
    on-failure: ABORT
    commands:
      - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    on-failure: ABORT
    commands:
      - docker build -t $REPOSITORY_URL:latest .
      - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG
  post_build:
    on-failure: ABORT
    commands:
      - docker push $REPOSITORY_URL:latest
      - docker push $REPOSITORY_URL:$IMAGE_TAG
      - 'jq -n --arg container $CONTAINER_NAME --arg image $REPOSITORY_URL:$IMAGE_TAG ''[{ "name": $container, "imageUri": $image }]'' > imagedefinitions.json'
